version: "3.7"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python /app/manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file: .env
    links:
      - postgres

  postgres:
    image: postgres:11
    ports:
        - "5432:5432"
    environment:
      POSTGRES_DB: docker
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: password
